### ISSUE TITLE
DioException 403

### ISSUE THREAD

**Issue by MaratelloMaJo** [sonic-liberation/spotube-plugin-spotify#14]
Hi, I Have some problems with plugin Spotify and I can't solve this problem

Logs:
DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

![Image](https://github.com/user-attachments/assets/55b5c4d4-00c2-47c7-a2a5-962b92965fcb)

**Comment by CharaIndompt** [comment]
Pretty sure that's Spotify that caught wind of it and acted to take it down...

**Comment by its-blue** [comment]
Seems like many have this issue.

**Comment by GulTion** [comment]
```
DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
```

Android 12
Version:5.0.0

**Comment by moisestohias** [comment]
same issue here

**Comment by 8wapnil** [comment]
Spotify trying hard to stop Spotube

**Comment by Ulysse2211** [comment]
Same error, but if it can help, the artist pages work just fine. Maybe just a changé in the api syntax?

**Comment by A3RABEY69-2** [comment]
![Image](https://github.com/user-attachments/assets/3fb883f7-5e39-4dd3-8ab8-3a52029a22b8)
I get the error, but I can still play songs from playlists in the "Recently Played" on the homepage

**Comment by aizigun** [comment]
DioException [bad response]: This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 403 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

**Comment by javiercuellar73** [comment]
+1

**Comment by thiagoo555** [comment]
This happened to me too.

<img width="1168" height="655" alt="Image" src="https://github.com/user-attachments/assets/6d70bee4-b814-4178-a8ca-b19fca034668" />

**Comment by 8wapnil** [comment]
Hey its fixed in the latest release!

**Comment by aizigun** [comment]
it works now

**Comment by lion099** [comment]
I'm still having this issue, even after updating 

<img width="1422" height="909" alt="Image" src="https://github.com/user-attachments/assets/2aec0955-54c9-4830-86e0-e40962af6a4d" />

**Comment by Ulysse2211** [comment]
@MaratelloMaJo maybe close the issue if it's also fixed for you.

**Comment by pizzav-xyz** [comment]
I'm still getting this

**Comment by nexion63** [comment]
it's same for me
